# Example configuration for remote Model Context Protocol (MCP) servers

[[mcp.remote_servers]]
name = "example-mcp"
url = "https://example-server.modelcontextprotocol.io/sse"
authentication = "oauth2"
# Optional: restrict the tools that can be used with this MCP server
# authorization_token = "<your-authorization-token>"
# tool_configuration.enabled = true
# tool_configuration.allowed_tools = [
#   "example_tool_1",
#   "example_tool_2",
# ]
#
# [[mcp.remote_servers]]
# name = "another-mcp"
# ...

[[mcp.remote_servers]]
name = "fetch-mcp"
url = "https://remote.mcpservers.org/fetch/mcp"
